import Navbar from '@/app/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/app/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'PIAIC Hackathon',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=''>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
